[package]
name = "lora-cli"
version = "0.1.0"
edition = "2021"

[features]
default = []
rpi = ["dep:rppal"]

[dependencies]
sx126x = { path = "../sx126x", features = ["std"] }
sx127x = { path = "../sx127x" }
anyhow = "1"
heapless = "0.8"
log = "0.4"
env_logger = "0.11"
clap = { version = "4", features = ["derive", "env"] }
ratatui = "0.28"
crossterm = "0.28"
serialport = "4"
embedded-io = { version = "0.6", features = ["std"] }
embedded-hal = "1.0"

[target.'cfg(target_os = "linux")'.dependencies]
rppal = { version = "0.19", optional = true, features = ["embedded-hal"] }
udev = { version = "0.9", features = ["send"] }
libc = "0.2"
